version: "3"

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  checkout:
    build:
      context: .
      dockerfile: checkout/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - zipkin
      - order
    environment:
      - ORDER_URL=http://order:8081
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    command:
      [
        "./checkout-service",
        "-http.addr=:8080",
        "-order.url=http://order:8081",
        "-zipkin.url=http://zipkin:9411/api/v2/spans",
      ]

  order:
    build:
      context: .
      dockerfile: order/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - zipkin
      - payment
      - inventory
      - address
    environment:
      - PAYMENT_URL=http://payment:8082
      - INVENTORY_URL=inventory:50051
      - ADDRESS_URL=http://address:8084
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    command:
      [
        "./order-service",
        "-http.addr=:8081",
        "-payment.url=http://payment:8082",
        "-inventory.url=inventory:50051",
        "-address.url=http://address:8084",
        "-zipkin.url=http://zipkin:9411/api/v2/spans",
      ]

  payment:
    build:
      context: .
      dockerfile: payment/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - zipkin
    environment:
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    command:
      [
        "./payment-service",
        "-http.addr=:8082",
        "-zipkin.url=http://zipkin:9411/api/v2/spans",
      ]

  inventory:
    build:
      context: .
      dockerfile: inventory/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - zipkin
    environment:
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    command:
      [
        "./inventory-service",
        "-http.addr=:8083",
        "-grpc.addr=:50051",
        "-zipkin.url=http://zipkin:9411/api/v2/spans",
      ]

  address:
    build:
      context: .
      dockerfile: address/Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - zipkin
    environment:
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    command:
      [
        "./address-service",
        "-http.addr=:8084",
        "-zipkin.url=http://zipkin:9411/api/v2/spans",
      ]

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["--jetstream"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  logstash:
    build:
      context: ./logstash
      dockerfile: Dockerfile
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
      - nats
